version: "3"

services:
    producer:
        build: ./producer
        environment:
            BROKER_URL: broker:9092
            TOPIC_NAME: data-input
            RESULT_TOPIC: data-output
            TOTAL_PARTITIONS: 10
            CLIENT_ID: test

    consumer:
        build: ./simple_consumer
        depends_on:
            - producer
            - redis
        environment:
            BROKER_URL: broker:9092
            TOPIC_NAME: data-input
            RESULT_TOPIC: data-output
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_LIST_NAME: mylist
    redis:
        image: bitnami/redis
        ports:
            - "6379:6379"
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
# Give this composition access to the Kafka network
networks:
    default:
        external:
            name: assignment-kafka-network
